name: buho_turismo
description: "Aplicación de turismo con Supabase"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.1
  image_picker: ^1.0.0
  intl: ^0.18.0
  url_launcher: ^6.1.10
  geolocator: ^10.1.0
  flutter_svg: ^2.0.7
  path_provider: ^2.1.2





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_buho.png
